/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import deepspace.EnemyToUI;
/**
 *
 * @author inaki
 */
public class EnemyView extends javax.swing.JPanel {

    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        repaint();
        revalidate();
    }

    public void setNombreEnemigo(EnemyToUI enemy){
        Enemigo.setText(enemy.getName());  //Se mete en el label del enemigo  el nombre del enemigo
    }
    
    public void setShieldPower(EnemyToUI enemy){

        ShieldPower.setText(Float.toString(enemy.getShieldPower()));
    }
    
    public void setAmmoPower(EnemyToUI enemy){
        AmmoPower.setText(Float.toString(enemy.getAmmoPower()));
    }
    
    public void setWeaponsDamage(EnemyToUI enemy){
        Weapons.setText(enemy.getDamage().getWeaponInfo());
        
    }
    
    public void setShieldsDamage(EnemyToUI enemy){
        Shields.setText(Integer.toString(enemy.getDamage().getNShields()));
    }
    
    public void setEnemy(EnemyToUI enemy){
        PanelLoot.removeAll();
        setNombreEnemigo(enemy);
        setShieldPower(enemy);
        setAmmoPower(enemy);
        LootView l=new LootView();
        l.setLoot(enemy.getLoot());
        PanelLoot.add(l);
        setWeaponsDamage(enemy);
        setShieldsDamage(enemy);
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAmmoPower = new javax.swing.JLabel();
        LabelShieldPower = new javax.swing.JLabel();
        AmmoPower = new javax.swing.JLabel();
        ShieldPower = new javax.swing.JLabel();
        LabelEnemigo = new javax.swing.JLabel();
        Enemigo = new javax.swing.JLabel();
        PanelLoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Weapons = new javax.swing.JLabel();
        Shields = new javax.swing.JLabel();

        LabelAmmoPower.setText("Potencia de fuego:");

        LabelShieldPower.setText("Potencia de defensa:");

        LabelEnemigo.setText("Enemigo:");

        PanelLoot.setBorder(javax.swing.BorderFactory.createTitledBorder("Botín"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Daño"));

        jLabel1.setText("Armas:");

        jLabel2.setText("Escudos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(Weapons))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(40, 40, 40)
                        .addComponent(Shields)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Weapons))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Shields))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelLoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAmmoPower)
                                    .addComponent(LabelShieldPower))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ShieldPower)
                                    .addComponent(AmmoPower)
                                    .addComponent(Enemigo)))
                            .addComponent(LabelEnemigo))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEnemigo)
                    .addComponent(Enemigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAmmoPower)
                    .addComponent(AmmoPower))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelShieldPower)
                    .addComponent(ShieldPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmmoPower;
    private javax.swing.JLabel Enemigo;
    private javax.swing.JLabel LabelAmmoPower;
    private javax.swing.JLabel LabelEnemigo;
    private javax.swing.JLabel LabelShieldPower;
    private javax.swing.JPanel PanelLoot;
    private javax.swing.JLabel ShieldPower;
    private javax.swing.JLabel Shields;
    private javax.swing.JLabel Weapons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
