/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;
import deepspace.LootToUI;
/**
 *
 * @author inaki
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    public void setArmas(LootToUI loot){
        Armas.setText(Integer.toString(loot.getnWeapons()));
    }
    
    public void setEscudos(LootToUI loot){
        Escudos.setText(Integer.toString(loot.getnShields()));
    }
    
    public void setCapacidad(LootToUI loot){
        Capacidad.setText(Integer.toString(loot.getnHangars()));
    }
    
    public void setCombustible(LootToUI loot){
        Combustible.setText(Integer.toString(loot.getnSupplies()));
    }
    
    public void setMedallas(LootToUI loot){
        Medallas.setText(Integer.toString(loot.getnMedals()));
    }
    public void setLoot(LootToUI l){
        setArmas(l);
        setEscudos(l);
        setCapacidad(l);
        setCombustible(l);
        setMedallas(l);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Labelarmas = new javax.swing.JLabel();
        Labelescudos = new javax.swing.JLabel();
        Labelcapacidad = new javax.swing.JLabel();
        Labelcombustible = new javax.swing.JLabel();
        Labelmedallas = new javax.swing.JLabel();
        Armas = new javax.swing.JLabel();
        Escudos = new javax.swing.JLabel();
        Capacidad = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        Medallas = new javax.swing.JLabel();

        Labelarmas.setText("Armas: ");

        Labelescudos.setText("Escudos: ");

        Labelcapacidad.setText("Capacidad del hangar: ");

        Labelcombustible.setText("Combustible");

        Labelmedallas.setText("Medallas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Labelescudos, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(Labelcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labelarmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Capacidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Labelmedallas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Medallas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Labelcombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Combustible)))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Escudos)
                            .addComponent(Armas))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelarmas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Armas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelcombustible)
                            .addComponent(Combustible))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelescudos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Escudos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelcapacidad)
                            .addComponent(Capacidad)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labelmedallas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Medallas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Armas;
    private javax.swing.JLabel Capacidad;
    private javax.swing.JLabel Combustible;
    private javax.swing.JLabel Escudos;
    private javax.swing.JLabel Labelarmas;
    private javax.swing.JLabel Labelcapacidad;
    private javax.swing.JLabel Labelcombustible;
    private javax.swing.JLabel Labelescudos;
    private javax.swing.JLabel Labelmedallas;
    private javax.swing.JLabel Medallas;
    // End of variables declaration//GEN-END:variables
}
